% \VignetteIndexEntry{Circular phylogenetic tree}
% \VignetteDepends{circlize}
% \VignetteKeywords{circos R}
% \VignetteKeywords{Phylogenetic tree}
% \VignetteKeywords{circlize}
% \VignettePackage{circlize}
%\VignetteCompiler{knitr}
%\VignetteEngine{knitr::knitr}

<<echo = FALSE>>=
library(knitr)
opts_chunk$set(fig.pos = "")

library(circlize)
circos.initialize = function(...) {
    circos.par(unit.circle.segments = 300)
    circlize::circos.initialize(...)
}
@

\documentclass{article}

\usepackage[T1]{fontenc}
\usepackage[sc]{mathpazo}
\renewcommand{\sfdefault}{lmss}
\renewcommand{\ttdefault}{lmtt}

\title{How to draw a phylogenetic tree}

\author{Zuguang Gu {\tt <z.gu@dkfz.de>}}
\usepackage[margin=1in, a4paper]{geometry}

\usepackage{hyperref}


\begin{document}

The vignette has been removed to \url{http://jokergoo.github.io/circlize_book/book/}.
The archive is still available at \url{http://jokergoo.github.io/circlize_old_vignettes/circular_phylogenetic_tree.pdf}.
This empty document will be deleted in the near future.

\end{document}
