# This file was generated by Rcpp::compileAttributes
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

estep <- function(A, L) {
    .Call('acc_estep', PACKAGE = 'acc', A, L)
}

estepAEE <- function(A, L, a) {
    .Call('acc_estepAEE', PACKAGE = 'acc', A, L, a)
}

makePanelMatrix <- function(T, M, UID, TGD, C) {
    .Call('acc_makePanelMatrix', PACKAGE = 'acc', T, M, UID, TGD, C)
}

matrixInverse <- function(S) {
    .Call('acc_matrixInverse', PACKAGE = 'acc', S)
}

rollSumCpp <- function(x, n) {
    .Call('acc_rollSumCpp', PACKAGE = 'acc', x, n)
}

